version: '2'
services:
  cli:
    environment:
      LAGOON_ENVIRONMENT_TYPE: 'ci'
    volumes:
      - .:/app:delegated
  php:
    environment:
      LAGOON_ENVIRONMENT_TYPE: 'ci'
    volumes:
      - .:/app:delegated
  nginx:
    environment:
      LAGOON_ENVIRONMENT_TYPE: 'ci'
    volumes:
      - .:/app:delegated
  selenium:
    image: selenium/standalone-chrome
    depends_on:
      - cli
