version: '2'
services:
  cli:
    build:
      context: .
      dockerfile: Dockerfile.builder
    image: builder
    environment:
      MYSQL_HOST: mariadb
    labels:
      lagoon.type: cli-persistent
      lagoon.persistent: /app/docroot/sites/default/files/
      lagoon.persistent.name: nginx-php
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    networks:
      - default
    labels:
      lagoon.type: nginx-php-persistent
      lagoon.persistent: /app/docroot/sites/default/files/
      lagoon.persistent.class: slow
      lagoon.name: nginx-php
    depends_on:
      - cli
    expose:
      - "8080"
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    labels:
      lagoon.type: nginx-php-persistent
      lagoon.persistent: /app/docroot/sites/default/files/
      lagoon.persistent.class: slow
      lagoon.name: nginx-php
    depends_on:
      - cli
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    labels:
      lagoon.type: mariadb
  redis:
    image: amazeeio/redis
    labels:
      lagoon.type: redis
