version: 2
jobs:
  build:
    machine: true
    working_directory: /home/circleci/project
    parallelism: 2
    steps:
      - checkout
      - run: env >> .env
      - run:
          name: Install lando
          command: |
            sudo apt-get update
            sudo apt-get -y install cgroup-bin
            sudo mkdir -p /usr/share/lando/bin/ && sudo ln -s /usr/local/bin/docker-compose /usr/share/lando/bin/docker-compose
            curl -fsSL -o /tmp/lando-latest.deb http://installer.lando.io/lando-latest-dev.deb
            sudo dpkg -i /tmp/lando-latest.deb
            lando version
      - run:
          name: Start lando
          command: |
            lando start
      - run: curl http://mysite.lndo.site
#      - run:
#          name: Site setup.
#          command: |
#            composer db-import
#            composer cli -- mkdir -p /app/screenshots
#      - run:
#          name: Install dev dependencies.
#          command: |
#            composer cli -- composer install --ansi
#            composer cli -- npm install
#      - run:
#          name: Lint code.
#          command: composer cli -- composer cs
#      - run:
#          name: Start Chrome in the background
#          command: google-chrome-stable --disable-gpu --headless --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222
#      - run:
#          name: Run tests.
#          command: composer cli -- vendor/bin/behat --format=progress_fail --colors --profile=p$CIRCLE_NODE_INDEX || composer cli -- vendor/bin/behat --format=progress_fail --colors --profile=p$CIRCLE_NODE_INDEX --rerun
#      - run:
#          name: Copy artifacts.
#          command: |
#            mkdir -p /tmp/artifacts/behat
#            docker cp $(docker-compose ps -q cli):/app/screenshots /tmp/artifacts/behat
#      - store_artifacts:
#          path: /tmp/artifacts
